# Generated by Django 5.0.6 on 2024-06-08 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidas',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saidas',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
